name: CI

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    build-site:
        name: Build website
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: pwsh-peek
        steps:
            - uses: actions/checkout@v4
            - uses: pnpm/action-setup@v4
              with:
                  version: 10.14.0
            - uses: actions/setup-node@v4
              with:
                  node-version: "20.19.0"
                  cache: "pnpm"
                  cache-dependency-path: pwsh-peek/pnpm-lock.yaml
            - run: pnpm install --frozen-lockfile
            - run: pnpm build

    test-module:
        name: Module tests (Pester)
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v4
            - name: Install Pester
              shell: pwsh
              run: |
                  Install-Module Pester -Force -Scope CurrentUser -MinimumVersion 5.5.0
            - name: Run tests
              shell: pwsh
              run: |
                  $env:PSModulePath = "$((Get-Location).Path);$env:PSModulePath"
                  Invoke-Pester -CI -Output Detailed
